export const DISPLAY_ALERT = "SHOW_ALERT";
export const DISPLAY_CUSTOM_ALERT = "SHOW_CUSTOM_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";
export const SET_TIMEOUT = "SET_TIMEOUT";

export const SETUP_USER_BEGIN = "SETUP_USER_BEGIN";
export const SETUP_USER_SUCCESS = "SETUP_USER_SUCCESS";
export const SETUP_USER_ERROR = "SETUP_USER_ERROR";

export const UPDATE_USER_BEGIN = "UPDATE_USER_BEGIN";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

export const SET_SHOWSIDEBAR = "SET_SHOWSIDEBAR";
export const TOGGLE_SHOPPINGCART = "TOGGLE_SHOPPINGCART";

export const LOGOUT_USER = "LOGOUT_USER";
